# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 123529f3da39098cd9b60c29bee87bb2e12ff18aeb1da3c05fa217f32087f013e64f1a0eac289503e6a413766313476068949a0c2246c17b8303ea9c1792662f

test:
  secret_key_base: bee53750b83a8dc249e094e18e0aea8626432c77a29efad460f6c54e7cc93ee62edf506a824fec29f48038a5ed8b3d29a0e76bd4524b2dad944853177cc792a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
